---
- hosts: all
  become: true
  remote_user: root

  tasks:
    - name: Install postfix
      yum:
        name: postfix
        state: latest

      tags:
        - server
      notify:
        - start_postfix

      
