---
- hosts: all
  become: True
  remote_user:  root

  tasks:
    - block:
        - uri:
            url:  "http://rhgls/access"
            copy: dest=/var/html/access.html content="I am accessible"

      rescue:
        - copy: dest=/var/html/access.html content="I have no access."

