--- 
- hosts: all
  become: true
  remote_user:  root

  tasks:
  - name: Create hostinfo.txt
    copy:
      dest: /root/hostinfo.txt
      content: "{{ansible_hostname}} {{ansible_processor_count }} {{ansible_enp0s3.ipv4.address}} {{ ansible_enp0s3.macaddress}}"
